### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getActiveView' of undefined

### ISSUE THREAD

**Issue by Jaswetz** [gangstead/atom-incremental-search#48]
[Enter steps to reproduce below:]

1. `CTRL + I`
2. Enter search term
3. `CMD + Enter`

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [incremental-search](https://github.com/gangstead/atom-incremental-search) package, v5.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getActiveView' of undefined

```
At /Users/jasonds/.atom/packages/incremental-search/lib/input-view.coffee:174

TypeError: Cannot read property 'getActiveView' of undefined
    at InputView.module.exports.InputView.focusEditor (/Users/jasonds/.atom/packages/incremental-search/lib/input-view.coffee:174:25)
    at space-pen-div.subscriptions.add.atom.commands.add.incremental-search:focus-editor (/Users/jasonds/.atom/packages/incremental-search/lib/input-view.coffee:40:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:38.2.0 grammar-selector:show (atom-text-editor.editor)
     -0:37 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:35.9.0 find-and-replace:show (a.inline-block)
     -0:34.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:32.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:30.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:30.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:26.9.0 find-and-replace:use-selection-as-find-pattern (atom-text-editor.editor.is-focused)
  3x -0:23.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.4.0 find-and-replace:confirm (atom-text-editor.editor.mini.is-focused)
     -0:18.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:13.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:12.7.0 incremental-search:forward (atom-text-editor.editor.is-focused)
  7x -0:06.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 incremental-search:focus-editor (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "useReactEditor": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.25.0
color-picker, v2.0.14
csslint, v1.1.4
editor-stats, v0.17.0
emmet, v2.3.17
highlight-line, v0.11.0
incremental-search, v5.0.1
linter, v1.11.3
linter-scss-lint, v2.5.0
pigments, v0.19.5

# Dev
No dev packages
```

**Comment by gangstead** [comment]
I think I fixed this with 84db5b7 can you try again with `v5.0.3`?

**Comment by Jaswetz** [comment]
@gangstead you still get an error on `CMD` + `Enter` but it works on just `Enter` or `CTRL` + `Enter`. It doesn't break at all either, you just get an error. I'd say it's fixed! Thanks a bunch for making this. It was the one thing Atom was missing.

**Comment by gangstead** [comment]
If this feature moves into Atom core I'll gladly unpublish the package.
